version: '3'
services:
    web:
        image: nginx:1.13.7-alpine
        volumes:
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./log:/var/log/nginx"
            - "./etc/nginx/default.template:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - ".env"
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php7.1
            - php5.6
            - mysqldb
            - myadmin
    php7.1:
        # image: nanoninja/php-fpm:7.1
        build: ./php7.1
        restart: always
        volumes:
            - "./etc/php7.1/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    php5.6:
        # image: nanoninja/php-fpm:5.6
        build: ./php5.6
        restart: always
        volumes:
            - "./etc/php5.6/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        # ports:
        #     - "8380:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"